### ISSUE TITLE
Diss

### ISSUE THREAD

**Issue by DresMArtin** [microsoft/vscode-data-wrangler#224]
Type: <b>Bug</b>

# Behaviour

## Expected vs. Actual

XXX

## Steps to reproduce:

1. XXX

# Diagnostic data

-   Jupyter extension version: Not installed
-   Python extension version: 2024.11.2024070901
-   .NET Install Tool for Extension Authors extension version: Not installed
-   Python package dependencies:

```json
N/A
```

-   Entrypoint: Command
-   Active mode: dataWrangler

Extension version: 1.4.1
VS Code version: Code 1.91.0 (Universal) (ea1445cc7016315d0f5728f8e8b12a45dc0a7286, 2024-07-01T18:54:18.541Z)
OS version: Darwin x64 23.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 070d0952-6b3a-4f24-9d01-365ad617fc6a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
dsvsc021:30996838
f3je6385:31013174
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
legacy_priority:31082724

```

</details>

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-data-wrangler/issues/195
- [ ] https://github.com/microsoft/vscode-data-wrangler/issues/220
- [ ] https://github.com/microsoft/vscode-data-wrangler/issues/223
```

**Comment by pwang347** [comment]
Hi @DresMArtin, thanks for opening this issue! Could you please provide some more description (e.g. a screenshot) or details for the issue you are encountering?

**Comment by pwang347** [comment]
Closing this issue due to inactivity, but please feel free to reopen if you can provide more details!
